spring:
  security:
    oauth2:
      client:
        registration:
          google:

            scope:
              - email
              - profile

  datasource:
      url: jdbc:postgresql://localhost:5432/SpringAuth
      driver-class-name: org.postgresql.Driver
      username: postgres

  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true






