services:
  postgres:
    image: postgres:16
    container_name: postgres

    environment:
      POSTGRES_DB: SpringAuth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PostgreSQL123

      ports:
        -"5432:5432"

  app:
    build: .
    container_name: springboot-app

    ports:
      - "8080:8080"

    depends_on:
      - postgres
